repo_url: https://pollomax847.github.io/assistant_entretien_chaudiere_pages/fdroid-technicien/fdroid/repo
repo_name: TechniChauff Private F-Droid (technicien)
archive_older: 3
archive_url: https://pollomax847.github.io/assistant_entretien_chaudiere_pages/fdroid-technicien/fdroid/repo/archive
keystore: fdroid.jks
keystorepass: IwaNmRWCN8vhioljCv9JdOrH
keypass: IwaNmRWCN8vhioljCv9JdOrH
repo_keyalias: upload
make_current_version_link: true
